version: 2.1
# add the snyk vulnerability service orb
orbs:
  snyk: snyk/snyk@0.0.8
jobs:
  build:
    docker:
      # This image has built-in chromium for e2e testing      
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      # checkout code from repo      
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # install the packages
      - run: yarn install
      # cache node_modules directory
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      # run lint test
      - run: yarn lint    
     
      # run cost analysis with size-limit  
      - run: yarn size

      # run tests!
      - run: yarn test

      # run vulnerability scan
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high

